// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.0
// source: query.sql

package db

import (
	"context"
	"database/sql"
)

const createUser = `-- name: CreateUser :exec
INSERT INTO users (
    user_name,
    password
) VALUES (?,?)
`

type CreateUserParams struct {
	UserName sql.NullString `json:"user_name"`
	Password sql.NullString `json:"password"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser, arg.UserName, arg.Password)
	return err
}

const getUser = `-- name: GetUser :one
SELECT id, user_name, password FROM users where user_name = ? LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, userName sql.NullString) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, userName)
	var i User
	err := row.Scan(&i.ID, &i.UserName, &i.Password)
	return i, err
}
